//------------------------------------------------------------------------------
// <auto-generated>
//     Bu kod araç tarafından oluşturuldu.
//     Çalışma Zamanı Sürümü:4.0.30319.42000
//
//     Bu dosyada yapılacak değişiklikler yanlış davranışa neden olabilir ve
//     kod yeniden oluşturulursa kaybolur.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Business.Localization {
    using System;
    
    
    /// <summary>
    ///   Yerelleştirilmiş dizeleri aramak gibi işlemler için, türü kesin olarak belirtilmiş kaynak sınıfı.
    /// </summary>
    // Bu sınıf ResGen veya Visual Studio gibi bir araç kullanılarak StronglyTypedResourceBuilder
    // sınıfı tarafından otomatik olarak oluşturuldu.
    // Üye eklemek veya kaldırmak için .ResX dosyanızı düzenleyin ve sonra da ResGen
    // komutunu /str seçeneğiyle yeniden çalıştırın veya VS projenizi yeniden oluşturun.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Localization {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Localization() {
        }
        
        /// <summary>
        ///   Bu sınıf tarafından kullanılan, önbelleğe alınmış ResourceManager örneğini döndürür.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Business.Localization.Localization", typeof(Localization).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Tümü için geçerli iş parçacığının CurrentUICulture özelliğini geçersiz kular
        ///   CurrentUICulture özelliğini tüm kaynak aramaları için geçersiz kılar.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Clinic Added benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string ClinicAdded {
            get {
                return ResourceManager.GetString("ClinicAdded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Clinic Deleted benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string ClinicDeleted {
            get {
                return ResourceManager.GetString("ClinicDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Clinic Listed benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string ClinicListed {
            get {
                return ResourceManager.GetString("ClinicListed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Clinic Name Invalid benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string ClinicNameInvalid {
            get {
                return ResourceManager.GetString("ClinicNameInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Clinics Listed benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string ClinicsListed {
            get {
                return ResourceManager.GetString("ClinicsListed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Clinic Updated benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string ClinicUpdated {
            get {
                return ResourceManager.GetString("ClinicUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Equipment Added benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string EquipmentAdded {
            get {
                return ResourceManager.GetString("EquipmentAdded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Equipment Deleted benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string EquipmentDeleted {
            get {
                return ResourceManager.GetString("EquipmentDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Equipment Listed benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string EquipmentListed {
            get {
                return ResourceManager.GetString("EquipmentListed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Equipment Name Invalid benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string EquipmentNameInvalid {
            get {
                return ResourceManager.GetString("EquipmentNameInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Equipments Listed benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string EquipmentsListed {
            get {
                return ResourceManager.GetString("EquipmentsListed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Equipment Updated benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string EquipmentUpdated {
            get {
                return ResourceManager.GetString("EquipmentUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   0.01 Or A Larger Value Must Be Entered In This Field benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string GreaterThan001 {
            get {
                return ResourceManager.GetString("GreaterThan001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   1 Or A Larger Value Must Be Entered In This Field benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string GreaterThan1 {
            get {
                return ResourceManager.GetString("GreaterThan1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   This Field Must Contain A Minimum Of 2 Character benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string MinLength2 {
            get {
                return ResourceManager.GetString("MinLength2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   This Field Should Not Be Left Blank benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string NotEmpty {
            get {
                return ResourceManager.GetString("NotEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   A Value Between 0.00 And 100.0 Must Be Entered In This Field benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string Range0100 {
            get {
                return ResourceManager.GetString("Range0100", resourceCulture);
            }
        }
    }
}
